- name: install utility packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "{{ vault_dependencies }}"

- name: Ensure remote vault dir exists
  file:
    path: /tmp/vault
    state: directory

- name: Add Vault group
  become: true
  group:
    name: "{{ vault_group }}"
    state: present

- name: Add Vault user
  become: true
  user:
    name: "{{ vault_user }}"
    comment: "Vault user"
    group: "{{ vault_group }}"
    system: true

- name: "Download Vault"
  get_url:
    url: "{{ vault_zip_url }}"
    dest: "/tmp/vault/vault.zip"

- name: Unarchive Vault and install binary
  unarchive:
    remote_src: true
    src: "/tmp/vault/vault.zip"
    dest: "{{ vault_bin_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"

- name: Cleanup
  file:
    path: "/tmp/vault"
    state: absent

- name: Ensure remote vault data dir exists
  file:
    path: /vault/data
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Ensure remote vault conf dir exists
  file:
    path: /etc/vault
    state: directory

- name: Vault configuration
  template:
    src: config.hcl.j2
    dest: /etc/vault/config.hcl
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"
