- name: Install Consul
  hosts: 
    - consul
  become: yes
  gather_facts: true
  connection: local
  vars_files:
    - vars/consul.yml
  roles:
    - base
    - brianshumate.consul
  pre_tasks:
    - debug:
        msg: "{{ groups['consul'] | map('extract', hostvars, 'ansible_eth1') | list }}"
        #var: "{{ groups['consul'] | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | join(',') }}"